// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooBitatApi;

#nullable disable

namespace ZooBitatApi.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230521144229_v0.1")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZooBitatApi.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EspecieIdEspecie")
                        .HasColumnType("int");

                    b.Property<string>("EstadoIdEstado")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HabitatIdHabitat")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitat")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Informacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAnimal");

                    b.HasIndex("EspecieIdEspecie");

                    b.HasIndex("EstadoIdEstado");

                    b.HasIndex("HabitatIdHabitat");

                    b.ToTable("Animales");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAsignacion");

                    b.ToTable("Asignacion");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Informacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEspecie");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Estado", b =>
                {
                    b.Property<string>("IdEstado")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("ZooBitatApi.Models.EstadoAsignacion", b =>
                {
                    b.Property<string>("IdEstadoAsignacion")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEstadoAsignacion");

                    b.ToTable("EstadosAsignacion");
                });

            modelBuilder.Entity("ZooBitatApi.Models.EstadoIncidencia", b =>
                {
                    b.Property<string>("IdEstadoIncidencia")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdEstadoIncidencia");

                    b.ToTable("EstadosIncidencia");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Habitat", b =>
                {
                    b.Property<int>("IdHabitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdTipoHabitat")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoHabitatIdTipoHabitat")
                        .HasColumnType("int");

                    b.HasKey("IdHabitat");

                    b.HasIndex("TipoHabitatIdTipoHabitat");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("ZooBitatApi.Models.HistorialEstado", b =>
                {
                    b.Property<string>("IdHistorialEstado")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AnimalIdAnimal")
                        .HasColumnType("int");

                    b.Property<string>("EstadoIdEstado")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdAnimal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdEstado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdHistorialEstado");

                    b.HasIndex("AnimalIdAnimal");

                    b.HasIndex("EstadoIdEstado");

                    b.ToTable("HistorialesEstado");
                });

            modelBuilder.Entity("ZooBitatApi.Models.HistorialHabitat", b =>
                {
                    b.Property<int>("IdHistorialHabitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalIdAnimal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdHistorialHabitat");

                    b.HasIndex("AnimalIdAnimal");

                    b.ToTable("HistorialesHabitat");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Incidencia", b =>
                {
                    b.Property<int>("IdIncidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalIdAnimal")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioMandante")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioMandanteIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdIncidencia");

                    b.HasIndex("AnimalIdAnimal");

                    b.HasIndex("UsuarioIdUsuario");

                    b.HasIndex("UsuarioMandanteIdUsuario");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Noticia", b =>
                {
                    b.Property<int>("IdNotica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdNotica");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador del zoologico"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Cuidador"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Veterinario"
                        },
                        new
                        {
                            IdRol = 4,
                            Nombre = "Visitante"
                        });
                });

            modelBuilder.Entity("ZooBitatApi.Models.TipoHabitat", b =>
                {
                    b.Property<int>("IdTipoHabitat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTipoHabitat");

                    b.ToTable("TiposHabitat");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolIdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("RolIdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Animal", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Especie", "Especie")
                        .WithMany()
                        .HasForeignKey("EspecieIdEspecie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooBitatApi.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooBitatApi.Models.Habitat", "Habitat")
                        .WithMany()
                        .HasForeignKey("HabitatIdHabitat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Estado");

                    b.Navigation("Habitat");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Habitat", b =>
                {
                    b.HasOne("ZooBitatApi.Models.TipoHabitat", "TipoHabitat")
                        .WithMany()
                        .HasForeignKey("TipoHabitatIdTipoHabitat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoHabitat");
                });

            modelBuilder.Entity("ZooBitatApi.Models.HistorialEstado", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalIdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooBitatApi.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("ZooBitatApi.Models.HistorialHabitat", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalIdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Incidencia", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalIdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooBitatApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooBitatApi.Models.Usuario", "UsuarioMandante")
                        .WithMany()
                        .HasForeignKey("UsuarioMandanteIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioMandante");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Noticia", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZooBitatApi.Models.Usuario", b =>
                {
                    b.HasOne("ZooBitatApi.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
